name: Run Tests and npm publish
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies - node_modules cache
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies - npm install-clean
        if: steps.node_modules_cache.outputs.cache-hit == 'false'
        run: npm install-clean

      - name: Run tests
        run: npm run test-ci

      - name: Generating tests coverage badges
        uses: "jpb06/jest-badges-action@latest"
        with:
          branches: main
          commit-message: "chore: Updating tests coverage badges [skip ci]"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies - node_modules cache
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies - npm install-clean
        if: steps.node_modules_cache.outputs.cache-hit == 'false'
        run: npm install-clean

      - name: Build
        run: npm run prepublish-me

      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: npm-module-build
          path: npm-module-build

  release:
    runs-on: ubuntu-latest
    needs: [ test, build ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies - node_modules cache
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies - npm install-clean
        if: steps.node_modules_cache.outputs.cache-hit == 'false'
        run: npm install-clean

      - name: Download build
        uses: actions/download-artifact@master
        with:
          name: npm-module-build
          path: npm-module-build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
#
#
#
#  test_and_release:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#
#      - name: Install
#        run: npm install-clean
#
#      - name: Run tests
#        run: npm run test-ci
#
#      - name: Generating coverage badges
#        uses: "jpb06/jest-badges-action@latest"
#        with:
#          branches: main
#          commit-message: "chore: Updating tests coverage badges [skip ci]"
#
#      - name: Build
#        run: npm run prepublish-me
#
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
#        run: npx semantic-release
