name: Run Tests and npm publish
on:
  push:
    branches:
      - main
jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install
        run: npm install-clean

      - name: Run tests
        run: npm run test-ci

      - name: Generating coverage badges
        uses: "jpb06/jest-badges-action@latest"
        with:
          branches: main
          commit-message: "chore: Updating tests coverage badges [skip ci]"

      - name: Build
        run: npm run prepublish-me

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx semantic-release
