name: Run Tests
on: [ push ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.1

      - name: Install
        run: pnpm i

      - name: Run tests
        run: pnpm run test-ci

      - name: Generating coverage badges
        uses: "jpb06/jest-badges-action@latest"
        with:
          branches: main
