name: Run Tests and npm publish
on:
  push:
    branches:
      - main
jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install
        run: npm install-clean

#      - name: Run tests
#        run: npm run test-ci
#
#      - name: Generating coverage badges
#        uses: "jpb06/jest-badges-action@latest"
#        with:
#          branches: main

      - name: Compare npm with local (versions)
        uses: Rober19/compare-npm-versions-ci@master
        id: package_version
        with:
          path: './'
          npm_package_name: pojo-constructor

      #      - name: Get version
      #        run: |
      #          echo "Version is  ${{ steps.package_version.outputs.version }} "
      #          echo "Version NPM is  ${{ steps.package_version.outputs.pkg_npm_version }} "
      #          echo "Is greater ${{steps.package_version.outputs.npm_is_greater}}"

      - name: Build
        if: steps.package_version.outputs.npm_is_greater == 'false'
        run: npm run prepublish-me

#      - name: Publish
#        uses: JS-DevTools/npm-publish@v1
#        if: steps.package_version.outputs.npm_is_greater == 'false'
#        with:
#          token: ${{secrets.NPM_TOKEN}}
#          package: ./npm-module/package.json
#          greater-version-only: true

      - name: token
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Author Identity
        run: git config --global user.email "dany.fedorov.d@gmail.com" && git config --global user.name "Dany Fedorov"

      - name: Publish
        run: npx release-it patch --ci
